platform :___VARIABLE_platform___, '___VARIABLE_version___'

pod '<#pod name#>'

#target :___PROJECTNAME___, :exclusive => true do
#end

#target :___PROJECTNAME___Tests, :exclusive => true do
#end

inhibit_all_warnings!
